- hosts: vm
  gather_facts: no
  become: true
  tasks:
  - name: Install apt packages
    tags:
      - install-packages
    apt:
      update_cache: true
      pkg:
        - fzf
        - ripgrep
        - zip
        - unzip
        - jq

- hosts: vm
  gather_facts: no
  tasks:
  - name: Install nvm
    git:
      repo: https://github.com/nvm-sh/nvm.git
      dest: /home/marc/.local/nvm
      clone: yes
      update: yes
  - name: Install node
    shell: source /home/marc/.nvm/nvm.sh && nvm install node
    args:
      executable: /bin/bash
  - name: Ensure default node
    shell: source /home/marc/.nvm/nvm.sh && nvm use node
    args:
      executable: /bin/bash
  - name: Ensure config dir
    file:
      path: /home/marc/.config/{{item}}
      state: directory
      mode: 0777
      recurse: yes
    loop:
      - nvim
  - name: Neovim config
    file:
      src: /home/marc/Projects/myutils/ansible/ubuntu/files/init.lua
      dest: /home/marc/.config/nvim/init.lua
      owner: marc
      group: marc
      state: link
  - name: Neovim Packer
    git:
      repo: https://github.com/wbthomason/packer.nvim
      dest: /home/marc/.local/share/nvim/site/pack/packer/start/packer.nvim
      clone: yes
      update: yes
  - name: Tmux config
    file:
      src: /home/marc/Projects/myutils/ansible/ubuntu/files/tmux.conf
      dest: /home/marc/.tmux.conf
      owner: marc
      group: marc
      state: link
  - name: Tmux plugins
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: /home/marc/.tmux/plugins/tpm
      clone: yes
      update: yes
  - name: ZSH config
    file:
      src: /home/marc/Projects/myutils/ansible/ubuntu/files/zshrc
      dest: /home/marc/.zshrc
      owner: marc
      group: marc
      state: link
  - name: ZSH auto suggestions
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: /home/marc/.zsh/plugins/zsh-autosuggestions
      clone: yes
      update: yes
  - name: ZSH highlight
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: /home/marc/.zsh/plugins/zsh-syntax-highlighting
      clone: yes
      update: yes
  - name: ZSH abreviation expansion
    git:
      repo: https://github.com/momo-lab/zsh-abbrev-alias.git
      dest: /home/marc/.zsh/plugins/zsh-abbrev-alias
      clone: yes
      update: yes
  - name: ZSH history search
    git:
      repo: https://github.com/joshskidmore/zsh-fzf-history-search.git
      dest: /home/marc/.zsh/plugins/zsh-fzf-history-search
      clone: yes
      update: yes
  - name: Ensure golang exists
    stat:
      path: /home/marc/.local/go/bin/go
    register: go_installed
  - name: Golang
    when: not go_installed
    block:
      - name: Download binaries
        get_url:
          checksum: sha256:956f8507b302ab0bb747613695cdae10af99bbd39a90cae522b7c0302cc27245
          url: https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
          dest: /tmp/golang-tmp.tar.gz
          mode: 0755
      - name: Decompress
        unarchive:
          src: /tmp/golang-tmp.tar.gz
          dest: /home/marc/.local/
      - name: Remove
        file:
          path: /tmp/golang-tmp.tar.gz
          state: absent
  - name: Config git
    file:
      src: /home/marc/Projects/myutils/ansible/ubuntu/files/gitconfig
      dest: /home/marc/.gitconfig
      owner: marc
      group: marc
      state: link
